-define(DEFAULT_STA_SSID, <<"your_ssdi">>).
-define(DEFAULT_STA_PSK, <<"your_psk">>).
-define(DEFAULT_NTP_HOST, "pool.ntp.org").
-define(DEFAULT_MQTT_URL, "mqtt.thingsboard.cloud").
-define(DEFAULT_MQTT_USER, "user").
-define(DEFAULT_MQTT_PSK, "psk").
-define(DEFAULT_MQTT_CLIENT, "higrow1").
-define(DEFAULT_MQTT_TOPIC, "esp/telemetry").
